name: remote update

on: push
jobs:
  job1:
    name: CI Project
    # Specify on which operating system we want this workflow to run
    runs-on: ubuntu-latest
    # The steps that will be excuted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.0"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: python -m pytest

  job2:
    name: Job 2
    # runs only if the steps of job1 succeeded
    needs: job1
    # Specify on which operating system we want this workflow to run
    runs-on: ubuntu-latest
    # The steps that will be excuted
    steps:
      - name: Configure SSH connection
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.SSH_PRIVATE_SECRET_KEY }}
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
          echo "$SSH_KEY" > ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/github_actions

      - name: Connect and pull
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run:
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }}
          && git checkout ${{ secrets.MAIN_BRANCH }}
          && git pull
          && exit"

      - name: Restart app
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} systemctl stop winc_cicd_assignment
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} systemctl restart winc_cicd_assignment

      - name: cleanup
        run: rm -rf ~/.ssh

  job3:
    name: Job 3
    # runs only if the steps of job2 succeeded
    needs: job2
    # now it will always run but waits for job2 to be finished even wenn it fails
    if: ${{ always() }}
    runs-on: ubuntu-latest
    # The steps that will be excuted
    steps:
      - name: Thank you message
        run: echo "Thanks for everything!"
